services:
  portfolio_app:
    container_name: portfolio_app_container
    image: ${DOCKER_HUB_USERNAME}/my-portfolio:${IMAGE_TAG:-latest}
    restart: always
    expose:
      - "3000"

  nginx:
    container_name: nginx_proxy_container
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - portfolio_app
